language: python
matrix:
    include:
        -   env: TOXENV=py27
        -   env: TOXENV=py35
            python: 3.5
        -   env: TOXENV=py36
            python: 3.6
        -   env: TOXENV=pypy
            python: pypy
        -   env:
            -   TOXENV=push
            -   secure: "Loi41DMkDbsjgIgeViKHTG7Wuw6m2vksNG3EodtrKvqoDT1ZtDy/upG/7yYArVQ98R+jX09nYAvV8YcqHAGhpMNiYapPqqvhC2rTP+coJNtRZPTIAGgQVmAQeYD9Qy4/+xNjAFCltn+pFE+5JnqyF4czbHqi3qQ+m03hGZPKhx2FHLrj32VbtxvrYSRiiocgqAropqG8gKAt3mit9Un5nYUtwlr89OaaQsc71e0PMSoL5dVDbmcn6WzaA7NkpHYOKjUFicziNK5wsRF0j7emEj5ZVnADYf7YU3Fs9WHgEPBZNZ3XK5F3mYDzvVHWN2+EY7eWyCvb30K3Mx2EaBgpimkVYU44d2R1ca/di96I6XmlEsImcOLTmF+pABhU8jZXhWiW+Znzj3iuInmAEaeNeisl2TMz3VYdDxRaTCPJXpICmEiJsX+ciei805Yq7rxqoo/YfkXqHdUMBw71exSTLHFgAm0sgEdtd0mJe1v5O+r3ACCS7r/FvwkT7GW+HFs1pnv/5AlAEuND+FPaHnqVdWlxaf1QN8oUR01GG/hR3nb7JDX60gJkKhHf7iS91ysjE9qq9SYWVkb2IlCGQOmaHQumuOeBAk/1b34Bg2o0EyWMJgyTHeGlpp6mXePjFQzqN47dKSP3Rp6IK0U+Z6D/qpvQpxGPXZqdGg/uvm6n9FI="
            python: 3.6
install: pip install coveralls tox
script: tox
after_success: coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
